spring:
  application:
    name: campus-timebank
  
  datasource:
    url: jdbc:postgresql://localhost:5432/campus_timebank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
      
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.campus.timebank: DEBUG
    org.springframework.security: DEBUG

app:
  jwt:
    secret: mySecretKeyForJWTTokenGenerationWhichShouldBeVeryLongAndSecure12345678
    expiration: 86400000  # 24 hours
  wallet:
    initial-balance: 10.00
